config/routes.rb
Rails.application.routes.draw do
  match '*any' => 'application#options', :via => [:options]
  root 'contacts#index'
  resources :contacts
  resources :accesses
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :accesses

  validates :email,
            format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/},
            :allow_blank => true
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :set_access, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /accesses
  # GET /accesses.json
  def index
    @accesses = Access.all
  end

  # GET /accesses/1
  # GET /accesses/1.json
  def show
  end

  # GET /accesses/new
  def new
    @access = Access.new
  end

  # POST /accesses
  # POST /accesses.json
  def create
    @access = Access.new(access_params)

    if !check_if_contact_exists(@access.contact_id)
      create_new_contact(@access.contact_id)
    end

    respond_to do |format|
      if @access.save
        format.html { redirect_to @access, notice: 'Access was successfully created.' }
        format.json { render :show, status: :created, location: @access }
      else
        format.html { render :new }
        format.json { render json: @access.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesses/1
  # DELETE /accesses/1.json
  def destroy
    @access.destroy
    respond_to do |format|
      format.html { redirect_to accesses_url, notice: 'Access was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_access
      @access = Access.find(params[:id])
    end

    def access_params
      params.require(:access).permit(:url, :contact_id)
    end

    def check_if_contact_exists (contact_id)
      Contact.exists?(contact_id)
    end

    def create_new_contact (contact_id)
      contact = Contact.new(id: contact_id)
      if !contact.save
        format.html { render :new }
        format.json { render json: contact.errors, status: :unprocessable_entity }
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:email, :name, :id)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/accesses/_form.html.erb
<%= form_with(model: access, local: true) do |form| %>
  <% if access.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access.errors.count, "error") %> prohibited this access from being saved:</h2>

      <ul>
      <% access.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accesses/edit.html.erb
<h1>Editing Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Show', @access %> |
<%= link_to 'Back', accesses_path %>

app/views/accesses/index.html.erb
<div class="container">
  <table class="responsive-table striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>Contato</th>
      <th>URL</th>
      <th>Data de Acesso</th>
    </tr>
    </thead>

    <tbody>
    <% @accesses.each do |access| %>
        <tr>
          <th><%= access.id %></th>
          <th><%= access.contact_id %></th>
          <th><%= access.url %></th>
          <th><%= access.created_at %></th>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/accesses/new.html.erb
<h1>New Access</h1>

<%= render 'form', access: @access %>

<%= link_to 'Back', accesses_path %>

app/views/accesses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_access_path(@access) %> |
<%= link_to 'Back', accesses_path %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Lista de Contatos</h2>

<div class="container">
  <table class="responsive-table striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <th><%= contact.id %></th>
          <th><%= contact.name %></th>
          <th><%= contact.email %></th>
          <th>
            <%= link_to 'Detalhes', contact %>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<div class="container">
  <h3>Contato <%= @contact.id %></h3>

  <table class="responsive-table striped">
    <thead>
    <tr>
      <th>ID</th>
      <th>URL</th>
      <th>Data de Acesso</th>
    </tr>
    </thead>

    <tbody>
      <% @contact.accesses.each do |access| %>
        <tr>
          <th><%= access.id %></th>
          <th><%= access.url %></th>
          <th><%= access.created_at %></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsContactTracking</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">RD Dashboard</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to 'Contatos', contacts_path %></li>
          <li><%= link_to 'Acessos', accesses_path %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>